### ISSUE TITLE
Pre-prod review for code, UI, and content

### ISSUE THREAD

**Issue by timoguin** [tiki/website#18]
We need to conduct a final review for code, UI, and content before we do a deployment. This will likely surface other issues.

**Comment by mike-audi** [comment]
Issues:
- https://github.com/tiki/website/issues/22
- https://github.com/tiki/website/issues/23
- https://github.com/tiki/website/issues/24
- https://github.com/tiki/website/issues/25
- https://github.com/tiki/website/issues/26
- https://github.com/tiki/website/issues/27

Because my estimates got stuck, I was not able to see the UI that is shown after so this list is definitely incomplete.
