### ISSUE TITLE
Cleanroom dropdown does not display correctly

### ISSUE THREAD

**Issue by mike-audi** [tiki/website#23]
### Reason

It looks like you did not select a cleanroom when in reality you did

### Description

When selecting a cleanroom from the dropdown list, the cleanroom id is not displayed in the box as selected, it remains blank. 

### Success Criteria

- [ ] when selecting a cleanroom, the id should appear in the box.

**Comment by timoguin** [comment]
Can you include a screenshot of what it looks like for you so I know for sure what you mean? I think you're talking about the id itself not displaying.

The current design only displays the name of the cleanroom, without the id. I don't think we need to display the id because the user doesn't need it for any of the UI interactions. And it would add a bit of unnecessary bloat to the display.
