### ISSUE TITLE
Estimate never times out

### ISSUE THREAD

**Issue by mike-audi** [tiki/website#26]
### Reason

Estimate was spinning forever, went over 30 minutes

### Description

When an estimate is calculating, if something goes wrong it just spins forever. There should a) if it's going to take more than a few seconds, there needs to be copy saying so. b) can the user close and move on in the meantime? if so, the messaging should say where to go. if not, it should say so. c) it should timeout after some time and relay an error to the user, there's no way an estimate should take > 10m or whatever we pick as the cutoff. 

also why can't customers create multiple estimates in parallel? 

probably worth using a design similar to how s3 handles exactly this in their console. 

### Success Criteria

- [ ] add a timeout
- [ ] design messaging copy
- [ ] update code for messaging copy

**Comment by timoguin** [comment]
Yep, I ran into this myself multiple times this week when queries failed on the backend. There is no way to cancel or close out of the operation either, so you have to do a full page refresh to get back to the query editor. When you do that, you lose the query you had typed out.

This is also closely related to the backend silently swallow query errors. I've created an issue for that problem here:

https://github.com/tiki/core-account-service/issues/343
